<?php

/// @cond INTERNAL_DOCS

/// @brief C2 CAOS commands dictionary
class C2CAOSCommands {
    /// @brief Returns an array of tokens.
    public static function GetTokens() {
        return array(
            //creation
            'new: scen',
            'new: simp',
            'new: cbtn',
            'new: comp',
            'new: part',
            'new: vhcl',
            'new: lift',
            'new: bkbd',
            'new: crea',
            'new: gene',
            'new: cbub',
            'new: bbtx',
            'new: rain',
            'tokn',
		
            'pupt',
            'puhl',
            'kill',
            'totl',
            'touc',
            'slim',
            'addv',
            'subv',
            'mulv',
            'divv',
            'modv',
            'negv',
            'andv',
            'orrv',
            'rndv',
            'setv',
            'bble',
            'star',
            'rtar',
            'wait',
            'anim',
            'over',
            'base',
            'prld',
            'mvto',
            'mcrt',
            'mvby',
            'mesg shou',
            'mesg sign',
            'mesg tact',
            'mesg writ',
            'mesg wrt+',
            'stm# shou',
            'stm# sign',
            'stm# tact',
            'stm# writ',
            'stim shou',
            'stim sign',
            'stim tact',
            'stim writ',
            'rmn#',
            'rmnd',
            'rmnr',
            'room',
            'delr',
            'deln',
            'door',
            'teco',
            'obst',
            'obdt',
            'obsv',
            'grnd',
            'isar',
            'asea',
            'spot',
            'knob',
            'kmsg',
            'part',
            'cabn',
            'dps2',
            'dpas',
            'gpas',
            'spas',
            'tele',
            'bbd: vocb',
            'bbd: vcb1',
            'bbd: word',
            'bbd: sohw',
            'bbd: emit',
            'bbtx',
            'bbt2',
            'bbfd',
            'cbrg',
            'cbrx',
            'rain',
            'sys: cmrp',
            'sys: cmra',
            'sys: camt',
            'sys: wpos',
            'rmsc',
            'rclr',
            'musc',
            'snde',
            'sndq',
            'sndc',
            'sndl',
            'plds',
            'stpc',
            'fade',
            'driv',
            'chem',
            'crea',
            'injr',
            'fire',
            'trig',
            'appr',
            'walk',
            'touc',
            'poin',
            'aim:',
            'say#',
            'say$',
            'sayn',
            'impt',
            'done',
            'ltcy',
            'drea',
            'drop',
            'mate',
            'snez',
		
	
	
            'dde: gids root',
            'dde: gids fmly',
            'dde: gids spcs',
            'dde: getb allr',
            'dde: getb rpty',
            'dde: getb rrct',
            'dde: getb newv',
            'dde: getb lvob',
            'dde: getb bioc',
            'dde: getb organ',
            'dde: getb emtr',
            'dde: getb',
            'dde: getb rctn',
            'dde: pic2',
            'dde: scrp',
            'dde: putv',
            'dde: nact',
            'dde: lneu',
            'dde: lcus',
            'dde: puts',
            'dde: getb data',
            'dde: getb cnam',
            'dde: getb ctim',
            'dde: getv monk',
            'dde: getb ovvd',
            'dde: putb',
            'dde: negg',
            'dde: panc',
            'dde: lobe',
            'dde: gene',
            'dde: word',
            'dde: cell',
            'dde: died',
            'dde: live',
            'dde: hatc',
            'dbug',
            'dbgv',
            'dbgm',
            'scrx',
            'lock',
            'unlk',
            'evnt',
            'rmev',
            'scor',
            'sys: edit',
            'sys: dmap',
            'sys: wtop',
            'sys: quit',
            'sys: abrt',
            'sys: wrld',
            'sys: conv',
		
            );
    }
}

/// @endcond
?>
